language: node_js
node_js:
  - '16'
branches:
  only:
  - main
  - develop
  - staging
  - master
install:
  - npm install
  - npx playwright install-deps

script:
  - npx playwright test --workers=1 --reporter=html --timeout=60000
